name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  Jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
