name: Jest Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Clear npm cache
        run: npm cache clean -f

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run Jest tests
        run: npm test
        working-directory: frontend
